### ISSUE TITLE
as a resident I require iconography to inform me at a glance whether a room is just right, too hot, too cold, too damp

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#103]

**Comment by Br3nda** [comment]
- [ ] too cold
- [ ] too hot (is this a thing?)
- [ ] too damp
- [ ] bit damp
- [ ] just right
- [ ] Humidity
- [ ] dewpoint
- [ ] temperature

**Comment by wharesync** [comment]
➤ brenda commented:

This story is only for the creation of images  -- e.g. png.

**Comment by wharesync** [comment]
➤ brenda commented:

Is this a task Benek is going to look at? Or should we attempt to find a local artist.

**Comment by Br3nda** [comment]
These appear to have been created by Benek! :-D
