### ISSUE TITLE
As a resident, I should be able to login with my registered credentials into Whare Hauora

### ISSUE THREAD

**Issue by amscraig** [WhareHauora/wharehauora-server#112]

**Comment by wharesync** [comment]
➤ brenda commented:

[Amber Craig](https://app.asana.com/0/386260511942709/386260511942709) i think we should flex out more of this story - based on what we find in the WHO docs

**Comment by wharesync** [comment]
➤ Amber Craig commented:

[brenda](https://app.asana.com/0/386260514599417/386260514599417) is this story about logging in or the report page?

**Comment by wharesync** [comment]
➤ brenda commented:

I was gonna ask u that ☺ you make this on github

**Comment by wharesync** [comment]
➤ brenda commented:

Let's make this the authentication story - and then close it
