### ISSUE TITLE
As a resident, i was to see what colour sticker a sensor has on it, shown in the UI, so i can work out which sensor is which.

### ISSUE THREAD

**Issue by amscraig** [WhareHauora/wharehauora-server#115]

**Comment by Br3nda** [comment]
Can you describe how a nick name varies from the current sensor names?
![image](https://cloud.githubusercontent.com/assets/12266/22402774/6dadf77a-e667-11e6-84ff-6c7bdd9588a5.png)

**Comment by Br3nda** [comment]
Working on this as part of #67

**Comment by Br3nda** [comment]
New approach: When we programme the initial firmware into the units, we'll also tell it what colour it is. (and we'll put a matching sticker on the unit).
The Sensor will send it's colour at startup (and periodically) and the Sensor::ingest rake task will need to decode this and save it - and make it visible in the UI

**Comment by Br3nda** [comment]
cancelled
