### ISSUE TITLE
as a resident, I require all my sensors graph to show me the timestamp of when the reading was taken

### ISSUE THREAD

**Issue by amscraig** [WhareHauora/wharehauora-server#134]

**Comment by jakerabid** [comment]
So here on these graphs, there are little dot's that show a discrete reading and when you hover the mouse over the dot it shows the time the reading was recorded - is this what you mean?

![screenshot](https://cloud.githubusercontent.com/assets/17534882/23535374/d2308080-0022-11e7-9c2b-ae119b033a80.png)

**Comment by Br3nda** [comment]
@jakerabid that's it yes. It was showing all times as midnight. So this is a bug

**Comment by amscraig** [comment]
@jakerabid yep - when I hover over some of the sensors in my home it gives me a reading of 12:00 however I tried to reproduce it and it seems to be working now for all my sensors.

**Comment by jakerabid** [comment]
huh, well if its working for you now then I guess next time I get to work on this I can double check it and close the bug :D Unless someone else gets to it first....

**Comment by Br3nda** [comment]
There's a bug. It cuts off data from today at midnight. So today's data doesn't show until you put tomorrow's date. And it defaults to today.

**Comment by Br3nda** [comment]
I'll file as a new bug
