### ISSUE TITLE
Home#show form should not allow negative days

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#146]

**Comment by Br3nda** [comment]
![image](https://cloud.githubusercontent.com/assets/12266/23772794/2d9535e8-0581-11e7-8104-2a0e54032e9c.png)

**Comment by Br3nda** [comment]
@jakerabid do you time to look at this one?

**Comment by Br3nda** [comment]
We also use pure css -- so the forms will get pretty if you use some of the classes from here:
https://purecss.io/forms/

**Comment by jakerabid** [comment]
I'll get onto this as soon as I can, which might not be until the 24th - but yeah, I can make it more pretty and also not allow negatives

**Comment by Br3nda** [comment]
Fixed
