### ISSUE TITLE
As a tenant, I want to see rooms of my whare compared to international and nz standards, so can make informed decisions about my home

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#152]
which standards?

room needs a type (living space? sleeping room?)
temperature now compared to an independent standard

**Comment by Br3nda** [comment]
Adding Amber, as she might have the answer to which standards we should build to first

**Comment by wharesync** [comment]
➤ Amber Craig commented:

[brenda](https://app.asana.com/0/386260514599417/386260514599417) so google has some standards so would be good to check where they get it from. WHO is a good standard to work from.

**Comment by wharesync** [comment]
➤ Amber Craig commented:

WHO standards

**Comment by wharesync** [comment]
➤ brenda commented:

do you have the details on the WHO standards?

**Comment by Kamikazilady** [comment]
Coving with Healthy home report and recording healthy home standards
