### ISSUE TITLE
As the "owner" of a home, i need to be able to remove whānau from my account, so I am assured they can no longer see data from my home.

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#155]

**Comment by Br3nda** [comment]
![image](https://cloud.githubusercontent.com/assets/12266/23968163/916d6a00-0a26-11e7-944a-b7bf5f6e5f47.png)
(the delete is only decorational right now - the code needs to be written)

**Comment by Br3nda** [comment]
@fauxparse this Story is a reasonable basic one and would be fabulous to close off.
The text is already there, but the UX i made sucks and doesn't actually work.

**Comment by fauxparse** [comment]
PR here: https://github.com/WhareHauora/wharehauora-server/pull/324
