### ISSUE TITLE
Menu doesn't wrap on mobile phones

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#297]
see screen shot
the menu makes the whole page too wide

![image](https://user-images.githubusercontent.com/12266/28766549-31b0b954-7624-11e7-8b76-c5e7f8e18bd2.png)

**Comment by amscraig** [comment]
Hi team - might be worth waiting to resolve this issue until we have the UI Designs for mobile. Might be worth spending our time working on the new designs, rather than fixing the UI of today?

**Comment by Br3nda** [comment]
Closing in favour of the new designs
