### ISSUE TITLE
Prepare production server

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#302]
We've been testing on staging - the production server needs a test - Will set up Community centre devices on production, and run from Rabid Technologies for several days

This will mean putting production server on the paid tier on heroku so heroku do not put the app to sleep .

**Comment by wharesync** [comment]
➤ brenda commented:

i've added the dns entry to iwantmyname about 5 times -- and it says it's succesdful, but when i look at the domain name again in iwantmy name it's not listed -- something's not working

I'll give it a bit of time and try again.

**Comment by Br3nda** [comment]
I've done the heroku end
```
=== whare Heroku Domain
whare.herokuapp.com

=== whare Custom Domains
Domain Name         DNS Target
──────────────────  ────────────────────────────────
app.wharehauora.nz  app.wharehauora.nz.herokudns.com
```

 but the bit on iwantmyname isn't working. - I've tried about ten times

![image](https://user-images.githubusercontent.com/12266/29491227-66d99400-85a8-11e7-885b-9629c440dea7.png)
![image](https://user-images.githubusercontent.com/12266/29491228-74b626f6-85a8-11e7-85bf-b490812c40d1.png)


it doesn't seem to be happening. The app is listing zero apps installed (there used to be square space installed!)

![image](https://user-images.githubusercontent.com/12266/29491234-9b7aec7c-85a8-11e7-9ade-91d7b71d24e2.png)

I'll wait a few more hours and try again.

**Comment by Br3nda** [comment]
Tried again -- iwantmyname just isn't saving the adding. I guess i add manually

**Comment by Br3nda** [comment]
I've set it up manually
https://app.wharehauora.nz
