### ISSUE TITLE
deliver deprecation warning

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#326]
DEPRECATION WARNING: `#deliver` is deprecated and will be removed in Rails 5. Use `#deliver_now` to deliver immediately or `#deliver_later` to deliver through Active Job. (called from create at /home/brenda/projects/wharehauora-server/app/controllers/invitations_controller.rb:17)

**Comment by fauxparse** [comment]
Oof, this was me. Before I fix it one way or the other: are we using ActiveJob at all, or should I just send it synchronously for now?

**Comment by Br3nda** [comment]
No active job used

**Comment by Br3nda** [comment]
Deliver now is good enough. We already have 2 workers on heroku. 3 is expensive
