### ISSUE TITLE
As a resident, I would like to invite my whānau&flatmates so they can also see our home, but retain the ability to remove their accounts later.

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#64]
On the exiting home/[id]/home_viewers page, there is a "add someone to whare"

It currently only succeeds if that user has already signed up with an account.

- [ ] Modify the controller action to also invite that user to whare hauora if they don't have an account yet.

![image](https://user-images.githubusercontent.com/12266/29592787-686c4908-87fa-11e7-94b0-8a76abaf2d70.png)

**Comment by Br3nda** [comment]
Can probably start without UX for now.

**Comment by jakerabid** [comment]
I'll have a go at this, but, can't work out how to assign it to myself....

**Comment by Br3nda** [comment]
You should have an invite to the wharehauora organisation. 
Have a look here:
http://github.com/wharehauora

**Comment by Br3nda** [comment]
Only works if the whānau is already a user. needs to invite them if not.

**Comment by Br3nda** [comment]
Un-assigned Jake.. Feel free to re-assign yourself if you're up for this one.
