### ISSUE TITLE
As the android dev, i need the web(rails) app to provide authentication so i can then manage a home's settings and read a home's data, over the api so i can display it in the android app

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#68]

**Comment by Br3nda** [comment]
Likely to use the doorkeeper gem

**Comment by joshmcarthur** [comment]
@Br3nda just so I'm clear with the requirement here: is this for an API that already exists, and I just don't see it in the code, or is this adding an authentication mechanism for an API that will exist in the future?

**Comment by Br3nda** [comment]
There isn't an api yet. Something using the jsonapi gem would be great. Needs authority added before (or at same time) then we can fill in the api
