### ISSUE TITLE
As administator I need to create/invite user to wharehauora by email

### ISSUE THREAD

**Issue by Br3nda** [WhareHauora/wharehauora-server#84]
- [ ] User with "janitor" role can create a user
- [ ] user receives an email inviting them to WhareHauora
- [ ] user can create a home, or admin can create the home when they invite the user
- [ ] admin an provision MQTT for the home (existing functionality)

**Comment by fauxparse** [comment]
Gonna pick this one up I think?

**Comment by Br3nda** [comment]
Assigned this to Vini - because she was asking me questions on slack - i think she's workin gon it.

@vinithanatarajan can you confirm so @fauxparse knows not to work on it too?

**Comment by Br3nda** [comment]
I might have this confused with #64.

@vinithanatarajan it's #64 you're working on, and not this, right?

**Comment by Br3nda** [comment]
Vini has replied on Slack - she's on this story

**Comment by fauxparse** [comment]
Oh. I was… almost done 😔

**Comment by vinithanatarajan** [comment]
That’s ok Matt, I am not yet done. If you want to do a PR that’s completely fine with me.

 -Vinitha.

**Comment by fauxparse** [comment]
Thanks, I smashed out most of it over my lunch break. Just need to build the email notification and I'm ready for a PR.

**Comment by Br3nda** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by fauxparse** [comment]
PR here: https://github.com/WhareHauora/wharehauora-server/pull/323

**Comment by Br3nda** [comment]
That PR actually implemented #64 . I'll close that one and re-open this.
